//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 SawChain_Check.rc 使用
//
#define IDD_SYSCTRL                     9
#define IDD_SYSCTRL2                    10
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_SYSCTRL1                    101
#define IDD_MainControl                 101
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_SawChain_CheckTYPE          130
#define IDR_PASTE_MENU                  151
#define IDR_WINDOWS_MENU                152
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_EDIT_MENU                   306
#define IDR_RIBBON                      307
#define IDD_DIALOG_MAINCONTROL          312
#define IDD_DIALOG_TOPCAM               313
#define IDD_DIALOG_BOTTOMCAM            314
#define IDD_INSTRUCTION                 315
#define IDC_BUTTON_CONVEYORSTOP         1000
#define IDC_BUTTON_CONVEYORCW           1001
#define IDC_BUTTON_ORIGIN               1001
#define IDC_BUTTON_CONVEYORCCW          1002
#define IDC_EDIT_DETECTED               1002
#define IDC_BUTTON_TGRAB                1003
#define IDC_BUTTON_BGRAB                1003
#define IDC_EDIT_DETECTED2              1003
#define IDC_BUTTON_PRESS_CYL            1003
#define IDC_COMBO_SEL_PRJ               1004
#define IDC_BUTTON_TDRAWRECT            1004
#define IDC_BUTTON_BTGRAB               1004
#define IDC_BUTTON_PUSH_CYL             1004
#define IDC_BUTTON_TGRAB2               1005
#define IDC_BUTTON_TSNAP                1005
#define IDC_EDIT_NGCOUNTER              1005
#define IDC_BUTTON_MAGNET_CYL           1005
#define IDC_BUTTON_TSHOW                1006
#define IDC_EDIT_CHAINLEN               1006
#define IDC_BUTTON_ADDNEWPRJ            1007
#define IDC_BUTTON_TSAVE                1007
#define IDC_BUTTON_MARK_CYL             1007
#define IDC_EDIT_TINVTHRESHOLD          1008
#define IDC_BUTTON_CHAINLEN             1008
#define IDC_BUTTON_MAGNET               1008
#define IDC_BUTTON_BTSNAP               1009
#define IDC_BUTTON_TDRAWREVRT           1009
#define IDC_BUTTON_ALERTSTOP            1009
#define IDC_EDIT_CHAINORDER             1009
#define IDC_BUTTON_BTSHOW               1010
#define IDC_BUTTON_TSHOWREVRT           1010
#define IDC_BUTTON_ISMARK               1010
#define IDC_BUTTON_BSHOWIMG             1010
#define IDC_EDIT_NGCHAINORDER           1010
#define IDC_BUTTON_BTSAVE               1011
#define IDC_EDIT_TINVLIMITSUP           1011
#define IDC_EDIT_TINVLIMITINF           1012
#define IDC_BUTTON_BDRAWREVRT           1012
#define IDC_BUTTON_INSTRUCTION          1012
#define IDC_BUTTON_TSAVE1               1013
#define IDC_BUTTON_BSHOWREVRT           1013
#define IDC_BUTTON_TSHOWRESULT          1014
#define IDC_EDIT_BINVLIMITSUP           1014
#define IDC_EDIT_BINVLIMITINF           1015
#define IDC_BUTTON_TSHOWRESULT2         1015
#define IDC_BUTTON_TSTARTTRAIN          1015
#define IDC_BUTTON_BSAVE                1016
#define IDC_BUTTON_TDRAWCHAR            1016
#define IDC_BUTTON_BSHOWRESULT          1017
#define IDC_BUTTON_TSHOWCHAR            1017
#define IDC_EDIT_BINVTHRESHOLD          1018
#define IDC_BUTTON_TSAVECHAR            1018
#define IDC_BUTTON1                     1019
#define IDC_BUTTON_TSHOWAREA            1019
#define IDC_BUTTON_BSTARTTRAIN          1019
#define IDC_EDIT_MAXVEL                 1020
#define IDC_BUTTON_TSHOWKNIFERT         1020
#define IDC_BUTTON_BDRAWCHAR            1020
#define IDC_EDIT_TACC                   1021
#define IDC_EDIT_INS                    1021
#define IDC_EDIT_TKNIFETHRESHOLD        1021
#define IDC_BUTTON_BSHOWCHAR            1021
#define IDC_BUTTON_CCW                  1022
#define IDC_EDIT_TMAXLEN                1022
#define IDC_BUTTON_BSAVECHAR            1022
#define IDC_BUTTON_CW                   1023
#define IDC_EDIT_TMINLEN                1023
#define IDC_EDIT_TACC2                  1024
#define IDC_BUTTON_TSAVEKNIFE           1024
#define IDC_EDIT_WAVES                  1024
#define IDC_BUTTON_TSHOWRESULT3         1025
#define IDC_EDIT_BKNIFETHRESHOLD        1026
#define IDC_BUTTON_TSAVEMODEL           1026
#define IDC_EDIT_BMAXLEN                1027
#define IDC_BUTTON_TMATCH               1027
#define IDC_EDIT_BMINLEN                1028
#define IDC_EDIT_TPRESION               1028
#define IDC_BUTTON_BDRAWKNIFERT         1029
#define IDC_BUTTON_TSAVECHARPARA        1029
#define IDC_BUTTON_BSHOWKNIFERT         1030
#define IDC_BUTTON_TDRAWUB              1030
#define IDC_BUTTON_BSAVEKNIFE           1031
#define IDC_BUTTON_TSHOWUB              1031
#define IDC_BUTTON_BSHOWRESULT3         1032
#define IDC_BUTTON_TTESTUB              1032
#define IDC_BUTTON_BSAVEMODEL           1033
#define IDC_STATIC_TPINV                1033
#define IDC_BUTTON_BMATCH               1034
#define IDC_STATIC_TPCHAR               1034
#define IDC_EDIT_BPRESION               1035
#define IDC_STATIC_TPKNIFE              1035
#define IDC_BUTTON_BSAVECHARPARA        1036
#define IDC_STATIC_BTINV                1036
#define IDC_STATIC_BTCHAR               1037
#define IDC_BUTTON_BDRAWUB              1037
#define IDC_STATIC_BTKNIFE              1038
#define IDC_BUTTON_BSHOWUB              1038
#define IDC_STATIC_DIEKNODE             1039
#define IDC_BUTTON_TTESTUB2             1039
#define IDC_BUTTON_BTESTUB              1039
#define IDC_STATIC_DOUBLEKNIFE          1040
#define IDC_STATIC_TPDAJI               1041
#define IDC_STATIC_TPDAJI2              1042
#define IDC_STATIC_BTDAJI               1042
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_BUTTON_SYSCTRL               32771
#define ID_BUTTON2                      32772
#define ID_BUTTON_SHOWTABLE             32772
#define ID_BUTTON_MOVEBACKWARD          32773
#define ID_BUTTON4                      32774
#define ID_BUTTON_FWD                   32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        316
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1041
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
